In [50]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
from patsy import dmatrices
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
from sklearn import metrics
from sklearn.cross_validation import cross_val_score


In [9]:
data = pd.read_excel('./default.xls', header = [0,1])

In [53]:
model = LogisticRegression()
train_cols = data.columns[2:]
model = model.fit(data[train_cols], np.ravel(data['Y']))

In [54]:
model.score(data[train_cols], np.ravel(data['Y']))

0.7789666666666667

In [55]:
# evaluate the model by splitting into train and test sets
X_train, X_test, y_train, y_test = train_test_split(data[train_cols], np.ravel(data['Y']), test_size=0.2, random_state=0)
model2 = LogisticRegression()
model2.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [57]:
# predict class labels for the test set
predicted = model2.predict(X_test)
print(predicted)

[0 0 0 ... 0 0 0]


In [59]:
# generate class probabilities
probs = model2.predict_proba(X_test)
print(probs)

[[0.67885217 0.32114783]
 [0.70143494 0.29856506]
 [0.76303741 0.23696259]
 ...
 [0.73587022 0.26412978]
 [0.63436865 0.36563135]
 [0.88435784 0.11564216]]


In [60]:
# generate evaluation metrics
print (metrics.accuracy_score(y_test, predicted))
print (metrics.roc_auc_score(y_test, probs[:, 1]))

0.7838333333333334
0.6283405447826


In [61]:
print (metrics.confusion_matrix(y_test, predicted))
print (metrics.classification_report(y_test, predicted))

[[4702    1]
 [1296    1]]
             precision    recall  f1-score   support

          0       0.78      1.00      0.88      4703
          1       0.50      0.00      0.00      1297

avg / total       0.72      0.78      0.69      6000



In [63]:
# evaluate the model using 10-fold cross-validation
scores = cross_val_score(LogisticRegression(), data[train_cols], np.ravel(data['Y']), scoring='accuracy', cv=10)
print (scores)
print (scores.mean())

[0.7784072  0.77907364 0.77874042 0.77874042 0.77833333 0.77866667
 0.80926976 0.77892631 0.77925975 0.77892631]
0.7818343806815977
